### PR TITLE
update overview matrix, chapters and capability files in sections

### PR DESCRIPTION
**Pull request by avaddict**
Update Latex to reflect the changes made to components and capabilities in the Data and Technology pillars.

### CODE REVIEW

**Comment by jgeluk** [comment]
@avaddict I see in this PR a lot of content being deleted but not moved to some place else or new content?

**Comment by avaddict** [comment]
@jgeluk most of the deletions are moves from data pillar to technology pillar. There are quite a few additions to the technology pillar. The remaining deletions cover some merging of capabilities in C-1, and the removal of capabilities that are unnecessary.

**Comment by jgeluk** [comment]
Many small files were missing (in taglines and summaries directories for instance), added those.
Chapter 4. Overview table (the one with the colors) still looks bad, didn't have time to fix that completely

**Review by rivettp — APPROVED** [review]
Happy with the changes/refactoring as I was present. Not able to review the PDF.

**Pull request merged**
